name: primextractor

services:
  app:
    image: primextractor
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    entrypoint: ./PrimextractorGUI.py
    command: -m dsa.ini
